version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ls -l
      - pwd
      - aws ecr get-login-password --region us-east-1
      - REPOSITORY_URI=public.ecr.aws/q0q1k1q6/demo-registry
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t demo-registry-private .
      - docker tag demo-registry-private:latest 595090880480.dkr.ecr.us-east-1.amazonaws.com/demo-registry-private:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 595090880480.dkr.ecr.us-east-1.amazonaws.com/demo-registry-private:latest
